[package]
name = "exemplar"
description = "A boilerplate eliminator for rusqlite."

version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
r2d2 = ["dep:r2d2", "dep:r2d2_sqlite"]

[dependencies]
exemplar_proc_macro = { version = "0.5.4" }
rusqlite = "0.29.0"

r2d2 = { version = "0.8.10", optional = true }
r2d2_sqlite = {version =  "0.22.0", optional = true }

[dev-dependencies]
anyhow = "1.0.75"
