[package]
name = "exemplar"
description = "A boilerplate eliminator for rusqlite."

version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["sql_enum"]

sql_enum = ["dep:num_enum"]

[dependencies]
exemplar_proc_macro = "0.5.0"
rusqlite = "0.29.0"

num_enum = { version = "0.7.0", optional = true}

[dev-dependencies]
anyhow = "1.0.75"
